channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python==3.6
  - numpy==1.14.3
  - scipy==1.1.0
  - scikit-learn==0.19.1
  - matplotlib==2.2.2
  - pandas==0.23.0
  - seaborn== 0.8.1
